# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Mdm"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# For session support enable the following line and see Dancer::Session
session: "YAML"

template: template_toolkit

baseurl: http://scratch.home.tomjudge.com:3000

plugins:
    DBIC:
        default:
            dsn: dbi:mysql:dbname=mdm;host=db-w
            schema_class: Mdm::DB
            user: amishhammer
            password: amishhammer
            options:
                RaiseError: 1
                PrintError: 1
    Email:
        headers:
            sender: 'webmaster@midwestdirtmafia.com'
            from: 'webmaster@midwestdirtmafia.com'
            subject: 'default subject'
            X-Mailer: 'Mdm 1.0'
            X-Accept-Language: 'en'

